app/urls.py
import datetime
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('', include('user.urls')),
    path('', include('base.urls')),
    path('company/', include('company.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = 'base.views.handler400'
handler403 = 'base.views.handler403'
handler404 = 'base.views.handler404'
handler500 = 'base.views.handler500'

document/urls.py
from django.urls import path 

from document import views
from document.models import DocumentType


urlpatterns = [
    path("", views.Index.as_view(), name="document-index"),

    path("document/<str:generictype>/create/", 
    views.DocumentCreateView.as_view(), name="document-document-create"),

    path("document/<str:generictype>/list/", 
    views.DocumentListView.as_view(), name="document-document-list"),

    #path("document/<str:generictype>/<int:pk>/", 
    #views.DocumentDetailView.as_view(), name="document-document-detail"),

    path("document/<str:generictype>/<int:pk>/update/", 
    views.DocumentUpdateView.as_view(), name="document-document-update"),

    path("document/<str:generictype>/<int:pk>/delete/", 
    views.DocumentDeleteView.as_view(), name="document-document-delete"),

    path("document/<str:generictype>/<int:pk>/print/", 
    views.DocumentPrintView.as_view(), name="document-document-print"),

    # Json views.

    path("api/document/<int:document>/", 
    views.document_detail_jsonview, 
    name="api-document-document-detail"),

    path("api/document/<int:document>/documentnote/create/", 
    views.document_note_create_jsonview, 
    name="api-document-document-documentnote-create"),

    path("api/document/<int:document>/documentnote/list/", 
    views.document_note_list_jsonview, 
    name="api-document-document-documentnote-list"),

    path("api/document/<int:document>/documentnote/delete/", 
    views.document_note_delete_jsonview, 
    name="api-document-document-documentnote-delete"),

    # django-autocomplete-light.

    path("autocomplete/documenttype/<str:generictype>/list/", 
    views.DocumentTypeAutocompleteView.as_view(),
    name="document-autocomplete-documenttype"),
]


# Creamos los path de forma dinámica para cada tipo genérico de documento, 
# para ser utilizado cuando se conoce el tipo genérico por anticipado.
# Útil por ejemplo para ser usado en la definición de módulos.

for generictype, verbose_name in DocumentType.GENERIC_TYPE_CHOICES:
    try:
        pattern_create = path(f"document/{generictype}/create/", 
            views.DocumentCreateView.as_view(generictype=generictype, 
            template_name=f"document/document/{generictype}_form.html"), 
            name=f"document-document-{generictype}-create")
    except (AttributeError):
        pass
    else:
        urlpatterns.append(pattern_create)
    
    try:
        pattern_list = path(f"document/{generictype}/list/", 
            views.DocumentListView.as_view(generictype=generictype), 
            name=f"document-document-{generictype}-list")
    except (AttributeError):
        pass
    else:
        urlpatterns.append(pattern_list)

    try:
        pattern_detail = path(f"document/{generictype}/<int:pk>/detail/", 
            views.DocumentDetailView.as_view(generictype=generictype), 
            name=f"document-document-{generictype}-detail")
    except (AttributeError):
        pass
    else:
        urlpatterns.append(pattern_detail)

    try:
        pattern_update = path(f"document/{generictype}/<int:pk>/update/", 
            views.DocumentUpdateView.as_view(generictype=generictype, 
            template_name=f"document/document/{generictype}_form.html"), 
            name=f"document-document-{generictype}-update")
    except (AttributeError):
        pass
    else:
        urlpatterns.append(pattern_update)

    try:
        pattern_delete = path(f"document/{generictype}/<int:pk>/delete/", 
            views.DocumentDeleteView.as_view(generictype=generictype), 
            name=f"document-document-{generictype}-delete")
    except (AttributeError):
        pass
    else:
        urlpatterns.append(pattern_delete)

    try:
        pattern_print = path(f"document/{generictype}/<int:pk>/print/", 
            views.DocumentPrintView.as_view(generictype=generictype), 
            name=f"document-document-{generictype}-print")
    except (AttributeError):
        pass
    else:
        urlpatterns.append(pattern_print)
    

document/models.py
from decimal import Decimal

from django.db import models
from django.db.models import Sum, F
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _l
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy

from unoletutils.libs import utils
from unoletutils.models import ModelBase
from finance.models import (Transaction)


def get_default_currency():
    """Obtiene la moneda marcada como predeterminada."""
    from finance.models import Currency
    return Currency.objects.filter(is_default=True).last()


class DocumentTypeActiveManager(models.Manager):
    """Obtiene los tipos de documentos activos."""

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class DocumentType(ModelBase):
    """
    Tipo de documento.
    """

    INVOICE = "invoice"
    INVOICE_RETURN = "invoice_return"
    PURCHASE = "purchase"
    PURCHASE_ORDER = "purchase_order"
    QUOTATION = "quotation"
    INVENTORY_INPUT = "inventory_input"
    INVENTORY_OUTPUT = "inventory_output"
    TRANSFER = "transfer"
    ACCOUNTING_INCOME = "accounting_income"
    ACCOUNTING_EXPENSE = "accounting_expense"
    GENERIC_TYPE_CHOICES = (
        (INVOICE, _l("Factura")),
        (INVOICE_RETURN, _l("Devolución en factura")),
        (PURCHASE, _l("Compra")),
        (PURCHASE_ORDER, _l("Orden de compra")),
        (QUOTATION, _l("Cotización")),
        (INVENTORY_INPUT, _l("Entrada de inventario")),
        (INVENTORY_OUTPUT, _l("Salida de inventario")),
        (TRANSFER, _l("Transferencia de inventario")),
        (ACCOUNTING_INCOME, _l("Ingreso contable")),
        (ACCOUNTING_EXPENSE, _l("Gasto contable")),
    )

    # INPUT, OUTPUT = "+", "-"
    # INVENTORY_CHOICES = (
    #     (INPUT, _l("Entrada")),
    #     (OUTPUT, _l("Salida")),
    # )

    CREDIT, DEBIT = "+", "-"
    ACCOUNT_CHOICES = (
        (CREDIT, _l("Crédito")),
        (DEBIT, _l("Débito")),
    )

    # Los tipos de este listado están habilitados para aceptar pagos.
    TYPES_THAT_CAN_ACCEPT_PAYMENTS = (INVOICE, INVOICE_RETURN, PURCHASE, 
        ACCOUNTING_INCOME, ACCOUNTING_EXPENSE)

    # Los tipos de este listado pueden afectar el inventario como entrada.
    TYPES_THAT_AFFECT_THE_INVENTORY_AS_INPUT = (INVENTORY_INPUT, PURCHASE,
        INVOICE_RETURN)

    # Los tipos de este listado pueden afectar el inventario como salida.
    TYPES_THAT_AFFECT_THE_INVENTORY_AS_OUTPUT = (INVENTORY_OUTPUT, INVOICE)

    # Los tipos de este listado pueden afectar el costo de artículos.
    TYPES_THAT_CAN_AFFECT_THE_COST = (INVOICE, INVOICE_RETURN, PURCHASE, 
        INVENTORY_INPUT, INVENTORY_OUTPUT)

    # Los tipos de este listado pueden afectar la cuenta por cobrar.
    TYPES_THAT_CAN_AFFECT_THE_ACCOUNT_RECEIVABLE = (INVOICE, ACCOUNTING_INCOME)

    # Los tipos de este listado pueden afectar la cuenta por pagar.
    TYPES_THAT_CAN_AFFECT_THE_ACCOUNT_PAYABLE = (PURCHASE, INVOICE_RETURN,
        ACCOUNTING_EXPENSE)

    code = models.CharField(_l("código"), max_length=6)

    name = models.CharField(_l("nombre"), max_length=70)

    generic = models.CharField(_l("tipo genérico"), max_length=20, 
    choices=GENERIC_TYPE_CHOICES, 
    help_text=_l("tipo genérico al que pertenece."))

    # affect_inventory = models.BooleanField(_l("afecta el inventario"), 
    # default=False, help_text=_l("Determina si los movimientos que se realicen "
    # "con este tipo de documento van a afectar el inventario de artículos."))

    affect_cost = models.BooleanField(_l("afecta el costo"), default=False, 
    help_text=_l("indica si el costo promedio de los artículos será calculado."))

    # affect_accounting_account = models.BooleanField(
    # _l("afecta las cuentas contable"), default=True, )

    tax_receipt = models.ForeignKey("finance.TaxReceipt", blank=True, null=True,
    on_delete=models.PROTECT, verbose_name=_l("comprobante fiscal"))

    is_active = models.BooleanField(_l("activo"), default=True)

    objects = models.Manager()

    active_objects = DocumentTypeActiveManager()

    class Meta:
        verbose_name = _l("tipo de documento")
        verbose_name_plural = _l("tipos de documentos")
        constraints = [
            models.UniqueConstraint(fields=("company", "code"), 
                name="unique_company_documenttype")
        ]

    def __str__(self):
        return self.code
    
    def clean(self):
        self.code = " ".join(self.code.split()).upper()
        
        other = DocumentType.objects.filter(
            company=self.company, code=self.code).exclude(pk=self.pk)
        if other:
            raise ValidationError({"code", 
                _("Ya existe otro tipo de documento con este código.")})

    def save(self, *args, **kwargs):
        self.code = " ".join(self.code.split()).upper()
        return super().save(*args, **kwargs)

    def accept_payments(self):
        """Determina si este tipo de documentos acepta pagos."""
        if self.generic in self.TYPES_THAT_CAN_ACCEPT_PAYMENTS:
            return True
        return False


class InputDocumentManager(models.Manager):
    """Manejador solo para documentos que afectan el inventario como entrada."""
    def get_queryset(self):
        return super().get_queryset().filter(
            doctype__inventory=DocumentType.INPUT)


class OutputDocumentManager(models.Manager):
    """Manejador solo para documentos que afectan el inventario como salida."""
    def get_queryset(self):
        return super().get_queryset().filter(
            doctype__inventory=DocumentType.OUTPUT)


class TransferDocumentManager(models.Manager):
    """Manejador para documentos de tipo transferencia."""
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(doctype__generic=DocumentType.TRANSFER)


class AcceptPaymentsDocumentManager(models.Manager):
    """Manejador solo para documentos que aceptan pagos."""
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(
            doctype__generic__in=DocumentType.TYPES_THAT_CAN_ACCEPT_PAYMENTS)


class Document(ModelBase):
    """
    Documento.
    """

    COMPANY_FIELD_NAME = "doctype__company"

    company = None # La empresa será doctype.company

    warehouse = models.ForeignKey("warehouse.Warehouse", 
    on_delete=models.PROTECT, help_text=_l("almacén del documento."))

    transfer_warehouse = models.ForeignKey("warehouse.Warehouse", blank=True,
    null=True, default=None, on_delete=models.PROTECT, 
    related_name="document_transfer_set", help_text=_l("almacén a transferir."))

    doctype = models.ForeignKey(DocumentType, on_delete=models.PROTECT,
    verbose_name=_l("tipo"))

    sequence = models.IntegerField(_l("secuencia"), editable=False, null=True)

    number = models.CharField(_l("número"), max_length=30, blank=True)

    date = models.DateField(_l("fecha"), default=timezone.now)

    expiration_date = models.DateField(_l("fecha de vencimiento"), 
    default=timezone.now, blank=True, null=True)

    person = models.ForeignKey("person.Person", on_delete=models.PROTECT, 
    null=True, blank=True, verbose_name=_l("persona"))

    person_name = models.CharField(_l("nombre de la persona"), max_length=100,
    blank=True)

    note = models.CharField(_l("nota"), max_length=500, blank=True)

    currency = models.ForeignKey("finance.Currency", on_delete=models.PROTECT,
    default=get_default_currency, null=True, verbose_name=_l("moneda"))

    currency_rate = models.DecimalField(_l("tasa de cambio"), max_digits=10, 
    decimal_places=4, default=1, blank=True, null=True,
    validators=[MinValueValidator(0)])

    tax_receipt_number = models.OneToOneField("finance.TaxReceiptNumber", 
    on_delete=models.PROTECT, editable=False, blank=True, null=True,
    verbose_name=_("número de comprobante fiscal"))

    pay_taxes = models.BooleanField(_l("paga impuestos"), default=True, 
    help_text=_l("determina si este documento paga impuestos."))

    is_printed = models.BooleanField(_l("Se imprimió"), default=False, 
    help_text=_l("indica si el documento ya fue impreso."))

    # Campos para consultas.

    amount = models.DecimalField(_l("importe"), max_digits=32, decimal_places=2,
    null=True, blank=True, editable=False)

    discount = models.DecimalField(_l("descuento"), max_digits=32, 
    decimal_places=2, null=True, blank=True, editable=False)

    tax = models.DecimalField(_l("impuesto"), max_digits=32, 
    decimal_places=2, null=True, blank=True, editable=False)

    total = models.DecimalField(_l("total"), max_digits=32, 
    decimal_places=2, null=True, blank=True, editable=False)

    # Seguimiento.

    create_user = models.ForeignKey(settings.AUTH_USER_MODEL, 
    on_delete=models.PROTECT, null=True, blank=True)

    create_date = models.DateTimeField(_l("fecha de creación"), 
    auto_now_add=True)

    # Manejadores.

    objects = models.Manager()

    # Documentos que afectan el inventario como entrada.
    input_document_objects = InputDocumentManager()

    # Documentos que afectan el inventario como salida.
    output_document_objects = OutputDocumentManager()

    # Documentos de tipo transferencia.
    transfer_objects = TransferDocumentManager()

    # Documentos que aceptan pagos.
    accept_payments_objects = AcceptPaymentsDocumentManager()

    class Meta:
        verbose_name = _l("documento")
        verbose_name_plural = _l("documentos")
        constraints = [
            models.UniqueConstraint(fields=("doctype", "sequence"), 
                name="unique_document_doctype_sequence")
        ]

    def __str__(self):
        return self.get_number()

    def get_reverse_kwargs(self):
        """Obtiene el diccionario para construir la URL con reverse."""
        return {"company": self.doctype.company.pk,

print/models.py
from django.db import models

from unoletutils.models import ModelBase



class PrintTemplate(ModelBase):
    """
    Plantilla de impresión.
    """
    tags = None

    name = models.CharField(_l("nombre"), max_length=100)

    content = models.TextField(_l("contenido"), help_text=_l("contenido de la "
    "plantilla en formato HTML."))

    class Meta:
        verbose_name = _l("plantilla de impresión")
        verbose_name_plural = _l("plantillas de impresión")
    
    def __str__(self):
        return self.name

    


    

print/views.py
from django.shortcuts import render

# Create your views here.

document/templates/document/document/inventory_input_form.html
{% extends 'document/document/form.html' %}

document/templates/document/document/inventory_output_list.html
{% extends 'document/document/list.html' %}

document/templates/document/document/invoice_form.html
{% extends 'document/document/form.html' %}

document/templates/document/document/invoice_list.html
{% extends 'document/document/list.html' %}

document/templates/document/document/invoice_print.html
{% extends 'document/document/print.html' %}

document/templates/document/document/list.html
{% extends 'document/list.html' %}


{% block actions %}
    {% create_button request model=object_list.model size="1.5rem" url=view.get_create_url %}
{% endblock %}

document/templates/document/document/print.html
{% extends 'base/print.html' %}
{% load i18n %}
{% load humanize %}
{% load base %}


{% block header %}
<div class="container-fluid">
    {% block headerTop %}{% endblock %}
    <div class="row">
        <div class="col col-5">
            {% block headerLeft %}
                <!-- {# company #} -->
                {% if object.warehouse.company.logo %}
                <img src="{{ object.warehouse.company.logo.url }}" alt="{{ object.warehouse.company }}" class="img-fluid">
                {% else %}
                <h2 class="display-3">{{ object.warehouse.company }}</h2>
                {% endif %}

                {% if object.warehouse.address %}
                <div>{{ object.warehouse.address }}</div>
                {% endif %}

                {% if object.warehouse.email %}
                <div>{% trans 'Email: ' %} {{ object.warehouse.email }}</div>
                {% endif %}

                {% if object.warehouse.phones %}
                <div>{% trans 'Tel.:' %} {{ object.warehouse.phones }}</div>
                {% endif %}
            {% endblock %}
        </div>
        <div class="col col-2">
            {% block headerCenter %}{% endblock %}
        </div>
        <div class="col col-5">
            {% block headerRight %}
                <!-- {# Invoice data #} -->
                <h1>{{ object.doctype.get_generic_display }}</h1>
                <table>
                    <tbody>
                        <tr>
                            <th>{% trans 'Sucursal: ' %}</th>
                            <td>{{ object.warehouse }}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Número: ' %}</th>
                            <td>{{ object.get_number }}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Fecha: ' %}</th>
                            <td>{{ object.date }}</td>
                        </tr>
                        <tr>
                            <th>{% trans 'Usuario: ' %}</th>
                            <td>{{ object.create_user }}</td>
                        </tr>
                    </tbody>
                </table>
            {% endblock %}
        </div>
    </div>
    <hr>
    {% block headerBottom %}{% endblock %}
</div>
{% endblock header %}

{% block main %}
<div class="container-fluid">
    {% block mainTop %}
        <!-- {# Movimientos. #} -->
        <table class="table table-sm">
            <thead>
                <tr>
                    <th class="text-start">{% trans 'Código' %}</th>
                    <th class="text-start">{% trans 'Descripción' %}</th>
                    <th class="text-end">{% trans 'Cantidad' %}</th>
                    <th class="text-end">{% trans 'Precio' %}</th>
                    <th class="text-end">{% trans 'Desc.' %}</th>
                    <th class="text-end">{% trans 'Impuesto' %}</th>
                    <th class="text-end">{% trans 'Total' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in object.get_movements %}
                <tr>
                    <td class="text-start">{{ obj.item.code }}</td>
                    <td class="text-start">{{ obj.name }}</td>
                    <td class="text-end">{{ obj.quantity|intcomma }}</td>
                    <td class="text-end">{{ obj.price|intcomma }}</td>
                    <td class="text-end">{{ obj.discount|intcomma }}</td>
                    <td class="text-end">{{ obj.tax|intcomma }}</td>
                    <td class="text-end">{{ obj.total|intcomma }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endblock %}
    <div class="row">
        <div class="col col-6">
            {% block mainLeft %}
                <!-- {# Nota. #} -->
                <p class="fw-bold">{{ object.note }}</p>
            {% endblock %}
        </div>
        <div class="col col-6">
            {% block mainRight %}
                <!-- {# Totales. #} -->
                <table class="table table-sm">
                    <tbody>
                        <tr>
                            <th class="text-end">{% trans 'Subtotal: ' %}</th>
                            <td class="text-end">{{ object.amount|intcomma }}</td>
                        </tr>
                        {% if object.discount %}
                        <tr>
                            <th class="text-end">{% trans 'Descuento: ' %}</th>
                            <td class="text-end">{{ object.discount|intcomma }}</td>
                        </tr>
                        {% endif %}
                        {% if object.tax %}
                        <tr>
                            <th class="text-end">{% trans 'Impuesto: ' %}</th>
                            <td class="text-end">{{ object.tax|intcomma }}</td>
                        </tr>
                        {% endif %}
                        <tr>
                            <th class="text-end fs-4">{% trans 'Total: ' %}</th>
                            <td class="text-end fw-bold fs-4">{{ object.total|intcomma }}</td>
                        </tr>
                    </tbody>
                </table>
            {% endblock %}
        </div>
    </div>
    {% block mainBottom %}{% endblock %}
</div>
{% endblock main %}

{% block footer %}
<div class="container-fluid">
    {% block footerTop %}{% endblock %}
    <div class="row">
        <div class="col col-5">
            {% block footerLeft %}{% endblock %}
        </div>
        <div class="col col-2">
            {% block footerCenter %}{% endblock %}
        </div>
        <div class="col col-5">
            {% block footerRight %}{% endblock %}
        </div>
    </div>
    {% block footerBottom %}{% endblock %}
</div>
{{ block.super }}
{% endblock footer %}

document/templates/document/document/purchase_form.html
{% extends 'document/document/form.html' %}

document/templates/document/document/purchase_list.html
{% extends 'document/document/list.html' %}

document/templates/document/document/purchase_order.html
{% extends 'document/document/list.html' %}

document/templates/document/document/quotation_list.html
{% extends 'document/document/list.html' %}

document/templates/document/document/transfer_form.html
{% extends 'document/document/form.html' %}

document/templates/document/document/transfer_list.html
{% extends 'document/document/list.html' %}