app/urls.py
import datetime
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('', include('user.urls')),
    path('', include('base.urls')),
    path('company/', include('company.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = 'base.views.handler400'
handler403 = 'base.views.handler403'
handler404 = 'base.views.handler404'
handler500 = 'base.views.handler500'

base/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),

    path("test/", views.TestView.as_view(), name="test"),
]

base/models.py
from django.db import models

company/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _l
from django.urls import reverse_lazy
from django.apps import apps
from django.utils.html import format_html

from unoletutils.libs import utils
from unoletutils.models import ModelBase

from module.models import Module


class Company(ModelBase):
    """
    Representa una empresa en la base de datos.

    Una empresa es una entidad que pertenece a un site y puede contener varios
    almacenes. Entonces las empresas tendrían el 2do nivel de prioridad después
    de los sites.
    """

    company = None
    tags = None

    site = models.ForeignKey(Site, on_delete=models.PROTECT, editable=False)

    users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    admin_users = models.ManyToManyField(settings.AUTH_USER_MODEL, 
    related_name="admin_users_company_set", blank=True)

    name = models.CharField(_l("nombre"), max_length=100,
    help_text=_l("nombre de la empresa para el público."))

    business_name = models.CharField(_l("Razón social"), max_length=100,
    help_text=_l("nombre legal registrado de la empresa."))

    logo = models.ImageField(_l("logo"), blank=True, 
    upload_to=utils.upload_file_on_site)

    is_active = models.BooleanField(_l("activo"), default=True)

    create_user = models.ForeignKey(settings.AUTH_USER_MODEL, 
    related_name="create_user_company_set", on_delete=models.PROTECT, null=True, 
    blank=True, editable=True)

    create_date = models.DateTimeField(auto_now_add=True, null=True, 
    blank=True, editable=False)

    objects = models.Manager()

    on_site = CurrentSiteManager()

    class Meta:
        verbose_name = _l("empresa")
        verbose_name_plural = _l("empresas")
        ordering = ["site", "name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy("company-company-detail", kwargs={"company": self.pk})

    def clean(self):
        if not self.pk:
            self.site = Site.objects.get_current()

    def save(self, *args, **kwargs):
        if not self.pk:
            # Cuando se registra una nueva empresa, se deberán crear los 
            # permisos de empresa para ella.
            out = super().save(*args, **kwargs)
            CompanyPermission.populate(company=self)
            return out
        return super().save(*args, **kwargs)
        
    def user_has_access(self, user) -> bool:
        """Comprueba si el usuario tiene acceso a esta empresa."""
        if (user in self.users.all()) or (user in self.admin_users.all()):
            return True
        return False

    def user_is_admin(self, user) -> bool:
        """Comprueba si el usuario es administrador en esta empresa."""
        if (user in self.admin_users.all()):
            return True
        return False
    
    def user_is_simple(self, user) -> bool:
        """Comprueba si el usuario tiene acceso pero no es administrador."""
        if (user in self.users.all()) and (not user in self.admin_users.all()):
            return True
        return False

    def get_user_list(self, is_active=True):
        """Obtiene todos los usuarios que tinen acceso a esta empresa."""
        qs = self.admin_users.all() | self.users.all()
        return qs.filter(is_active=is_active)

    def get_cascading_modules(self, parent=None):
        out = []
        for obj in Module.objects.filter(parent=parent):
            out.append({
                "name": _(obj.name), 
                "description": _(obj.description),
                "url": obj.build_url(company=self.pk),
                "svg": format_html(obj.get_svg(fill="white")["svg"]),
                "childrens": self.get_cascading_modules(parent=obj),
                "css_bgcolor": obj.css_bgcolor,
                "css_textcolor": obj.css_textcolor,
            })
        return out

    def get_warehouse_list(self, is_active=True):
        """Obtiene los almacenes de esta empresa."""
        return self.warehouse_set.filter(is_active=is_active)

    def has_warehouse(self, warehouse):
        """Comprueba si el almacén activo pertenece a esta empresa."""
        if warehouse in self.get_warehouse_list():
            return True
        return False


class CompanyPermission(ModelBase):
    """
    Permiso dentro de una empresa.

    Este modelo define los permisos personalizados de forma extraordinaria para
    este proyecto. Estos serán asignados a los usuarios por empresa (no global).

    Por ejemplo: El sistema necesita restringir a los usuarios, tal y como se 
    haría utilizando los permisos predeterminados de Django, pero en este caso
    los permisos serán asignados por empresa y no de forma Global. Esto hará 
    que un usuario tenga un permiso determinado en una empresa, pero en otra 
    empresa puede que no lo tenga.

    Estos permisos no serán gestionados por Django, sino que el sistema en si
    contará con su propio sistema de validación de permisos.

    Esto tampoco afectará los permisos predeterminados de Django, ni tampoco 
    afectará la forma de acceder al panel de administración de Django.

    ¿Cómo funciona?
    De lo más simple. Se registra el permiso, asignamos el permiso al usuario,
    establecemos el codename del permisos en la vista como permission_required,
    luego se determinará si el usuario pertenece a la empresa que intenta 
    acceder y si dicho usuario tiene asignado el permiso requerido.
    """

    APP_LABELS = (
        ("user", _l("usuario")), 
        ("audit", _l("auditoría")), 
        ("company", _l("empresa")), 
        ("warehouse", _l("almacén")), 
        ("document", _l("documento")), 
        ("finance", _l("finanzas")),
        ("inventory", _l("inventario")),
        ("person", _l("persona")),
    )

    ACTIONS = (
        ("view", _l("ver")), 
        ("add", _l("agregar")),
        ("change", _l("modificar")),
        ("delete", _l("eliminar"))
    )

    tags = None

    codename = models.CharField(_l("código"), max_length=50, editable=False)

    name = models.CharField(_l("nombre"), max_length=100)

    description = models.CharField(_l("descripción"), max_length=500, blank=True)

    class Meta:
        verbose_name = _l("permiso por empresa")
        verbose_name_plural = _l("permisos por empresa")
        ordering = ["company", "codename", "name"]
        constraints = [
            models.UniqueConstraint(fields=("company", "codename"), 
                name="unique_companypermission_codename"),
            models.UniqueConstraint(fields=("company", "name"), 
                name="unique_companypermission_name"),
        ]

    def __str__(self):
        return self.name

    def clean(self):
        self.codename = self.format_codename(self.codename, allowed="_.")
        self.name = " ".join(self.name.split())
        self.description = " ".join(self.description.split())

    @classmethod
    def populate(cls, company: Company=None, generic_permissions: list=None):
        """
        Registra los permisos para cada empresa registrada, o solo para la 
        empresa indicada.
        """
        if not generic_permissions:
            generic_permissions = []

            for app_label, app_title in cls.APP_LABELS:
                try:
                    models = list(apps.get_app_config(app_label).get_models())
                except (BaseException) as e:
                    raise e.__class__(f"{app_label}. {e}") from e

                for model in models:
                    if "historical" in model._meta.model_name:
                        continue
                    for action, action_title in cls.ACTIONS:
                        codename = f"{app_label}.{action}_{model._meta.model_name}".lower()
                        name = f"{action_title} {model._meta.verbose_name}".title()
                        generic_permissions.append((codename, name))

        if company != None:
            # Se borran los permisos que no estén en generic_permissions. Puede
            # ser que se crearon en un momento, pero ya el modelo o aplicación
            # por la que fueron creados ya no existe.
            db_codenames = CompanyPermission.objects.values_list("codename", flat=True)
            delete_codenames = []
            for db_codename in db_codenames:
                if not db_codename in dict(generic_permissions).keys():
                    delete_codenames.append(db_codename)
            CompanyPermission.objects.filter(codename__in=delete_codenames).delete()

            for codename, name in generic_permissions:
                permission = CompanyPermission(
                    company=company, codename=codename, name=name)
                permission.clean()
                # El permiso se creará solo si no existe.
                try:
                    CompanyPermission.objects.get(company=company, 
                        codename=permission.codename)
                except (CompanyPermission.DoesNotExist):
                    permission.save()
            return
        
        for company in Company.objects.all():
            cls.populate(company, generic_permissions)


class CompanyPermissionGroup(ModelBase):
    """
    Grupos (como los django.auth.Group) pero para CompanyPermission.

    Para trabajar los permisos de acceso por empresa.
    """
    tags = None

    codename = models.CharField(_l("código"), max_length=50)

    name = models.CharField(_l("nombre"), max_length=100)

    permissions = models.ManyToManyField(CompanyPermission, 
    verbose_name=_l("permisos"))

    class Meta:
        verbose_name = _l("grupo de permiso por empresa")
        verbose_name_plural = _l("grupos permisos por empresa")

print/models.py
from django.db import models

from unoletutils.models import ModelBase



class PrintTemplate(ModelBase):
    """
    Plantilla de impresión.
    """
    tags = None

    name = models.CharField(_l("nombre"), max_length=100)

    content = models.TextField(_l("contenido"), help_text=_l("contenido de la "
    "plantilla en formato HTML."))

    class Meta:
        verbose_name = _l("plantilla de impresión")
        verbose_name_plural = _l("plantillas de impresión")
    
    def __str__(self):
        return self.name

    


    

base/forms.py
from django import forms
import warnings
from django.core.exceptions import FieldError
from django.utils.html import format_html
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _l

from unoletutils.libs import icons


class ModelForm(forms.ModelForm):
    """
    Clase ModelForm base para los formularios de modelos que 
    requieren la 'company' instancia.
    """

    def __init__(self, *args, **kwargs):
        try:
            self.company = kwargs.pop("company")
        except (KeyError):
            warnings.warn("El formulario '{self}' no tiene la instancia 'company'.")
            self.company = None

        super().__init__(*args, **kwargs)

        self.set_company_to_instance(self.instance, self.company)
        self.set_company_to_company_field(self.fields.get("company"), self.company)

        # Los campos que tenga un 'queryset' atributo, como ModelChoiceField...
        # dicho queryset será filtrado por la empresa actual.
        for key in self.fields:
            if key == "company":
                continue
            field = self.fields[key]
            if hasattr(field, "queryset"):
                qs = field.queryset
                try:
                    qs = qs.filter(**{qs.model.COMPANY_FIELD_NAME: self.company})
                except (FieldError) as e:
                    raise FieldError(key, "Debe establecer la variable "
                        "COMPANY_FIELD_NAME en el modelo, apuntando a la campo "
                        "que contiene la 'compnay' instancia.", e)
                self.fields[key].queryset = qs

    def __getitem__(self, name):
        """Return a BoundField with the given name."""
        try:
            field = self.fields[name]
        except (KeyError):
            return super().__getitem__(name)

        # En negrita el label del campo requerido.
        if field.required:
            field.widget.attrs.update({"placeholder": field.label})
            field.label = format_html("<b>{}</b>", field.label)

        # Alineamos los campos numéricos a la derecha.
        if isinstance(field.widget, forms.NumberInput):
            field.widget.attrs.update({"class": "text-end"})

        # Establecemos el widget ideal para campos de fechas.
        if isinstance(field, forms.DateField):
            field.widget = forms.DateInput(attrs={"type": "date"})
        
        return super().__getitem__(name)

    def set_company_to_instance(self, instance, company):
        """Establece el objeto 'company' a la instancia."""
        if instance and company:
            if not instance.pk:
                if hasattr(instance, "company"):
                    instance.company = company

    def set_company_to_company_field(self, field, company, disabled=True):
        """
        Establece el objeto 'company' al campo donde se establece. Este 
        campo deberá ser un ChoiceModelField.
        """
        if field and company:
            field.queryset = company._meta.model.objects.filter(pk=company.pk)
            field.initial = company
            field.disabled = bool(disabled)
            field.label = ""
            field.widget.attrs.update({"style": "display: none"})


class SearchForm(forms.Form):
    """Formulario para búsqueda."""

    tags__icontains = forms.CharField(label="", max_length=50, strip=True, 
    required=False, widget=forms.TextInput(
        attrs={"type": "search", "placeholder": _l("Buscar...")}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

base/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView)
from django.contrib.auth.mixins import (LoginRequiredMixin, 
    PermissionRequiredMixin)


def handler400(request, exception=None):
    response = render(request, "error/400.html", {})
    response.status_code = 400
    return response


def handler403(request, exception=None):
    response = render(request, "error/403.html", {})
    response.status_code = 403
    return response


def handler404(request, exception=None):
    response = render(request, "error/404.html", {})
    response.status_code = 404
    return response


def handler500(request, exception=None):
    response = render(request, "error/500.html", {})
    response.status_code = 500
    return response


class IndexView(LoginRequiredMixin, TemplateView):
    """Página principal."""

    template_name = "base/index.html"


class TestView(LoginRequiredMixin, TemplateView):
    """Vista para realizar pruebas de diseño y javascript."""

    template_name = "base/test.html"

print/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base/base.html
{% load i18n %}
{% load humanize %}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ request.site.name }} {% if title %}| {{ title }}{% endif %}{% endblock %}</title>

    <script src="/static/external/jquery/jquery-3.5.1.js"></script>
    <link rel="stylesheet" href="/static/external/bootstrap/bootstrap-5.0.0-beta1-dist/css/bootstrap.css">
    <script src="/static/external/bootstrap/bootstrap-5.0.0-beta1-dist/js/bootstrap.bundle.js"></script>

    <script src="/static/js/table-resize.js"></script>
    <script src="/static/js/utils-1.1.js"></script>
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/components.css">

    <!-- <link rel="stylesheet" href="/static/css/darkmode-1.1.css"> -->

</head>

<body class="container-fluid p-0" style="overflow: auto;">

    {% block navbar %}
    <!-- {# Barra de navegación #} -->
    <div class="position-relative d-print-none">
        <nav class="navbar navbar-expand-lg navbar-light bg-white border w-100">
            <div class="container-fluid">
                <div class="">
                    <a class="navbar-brand" href="{% if company %}{{ company.get_absolute_url }}{% else %}{% url 'index' %}{% endif %}">
                        {% if company.logo %}
                            <img src="{{ company.logo.url }}" alt="{{ company }}" style="height: 2rem; max-width: 20rem;">
                        {% elif company %}
                            {{ company }}
                        {% else %}
                            {{ request.site.name }}
                        {% endif %}
                    </a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item" title="{% trans 'Página principal' %}">
                            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">{% svg 'house-fill' %}</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" title="{{ user }}">
                                {% svg 'person-fill' %}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">{{ user }}</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Cerrar sesión' %}</a></li>
                            </ul>
                        </li>
                        <li class="nav-item" title="{% trans 'Nofificaciones' %}">
                            <a class="nav-link active" aria-current="page" href="#">{% svg 'bell-fill' %}</a>
                        </li>
                        <li class="nav-item" title="{% trans 'Configuración' %}">
                            <a class="nav-link" href="#">{% svg 'gear-fill' %}</a>
                        </li>
                        <!-- <li class="nav-item">
                            <form class="d-flex">
                                <input class="form-control me-2" type="search" placeholder="{% trans 'Buscar' %}" aria-label="Search">
                            </form>
                        </li> -->
                    </ul>
                    {% breadcrumb request %}
                </div>
            </div>
        </nav>
    </div>
    {% endblock navbar %}


    {% block frame %}
    <div class="row px-2 pb-5">
        <aside id="section-left" class="col col-12 col-sm-12 col-md-3 col-lg-2 bg-white border-end pt-2 d-print-none">
            {% block frame_left %}
            <nav aria-label="Docs navigation">
                {% block frame_left_nav %}
                    {% menu request %}
                {% endblock %}
            </nav>
            {% endblock %}
        </aside>
        <div id="section-main" class="col col-12 col-sm-12 col-md-9 col-lg-10 h-100 px-0">
            {% block frame_right %}
            <aside class="border-bottom container-fluid py-2 bg-white shadow-sm d-print-none">
                {% block frame_right_top %}
                <div class="row">
                    <div class="col col-12 col-sm-8">
                        <h1 class="mb-0">{% block subtitle %}{% firstof view.get_title object %}{% endblock %}</h1>
                    </div>
                    <div class="col col-12 col-sm-4 text-end h1 mb-0">
                        {% block actions %}
                            {% list_action_links_for_object object %}
                        {% endblock %}
                    </div>
                </div>
                {% endblock %}
            </aside>
            <main class="pt-3 pb-1" style="height: 600px; overflow: auto;" id="main">
                <div class="container">
                    {% bootstrap_messages request %}
                </div>
                
                <!-- {# Block contenido principal. #} -->
                <div class="d-print-none">
                    {% block content %}
                    {% endblock content %}
                </div>

                <!-- {# block visible solo en la impresión. #} -->
                <div class="d-none d-print-block">
                    {% block print %}
                    {% endblock print %}
                </div>

                <!-- {# informaición de depuración #} -->
                <div class="d-print-none">
                    {% if settings.DEBUG == True and request.GET.show_developer_data %}
                        {% developer_data view request %}
                    {% endif %}
                </div>
            </main>
            {% endblock %}
        </div>
    </div>
    {% endblock %}

    <footer class="bg-dark">
        {% block footer %}
        {% endblock footer %}
    </footer>
</body>

<script>
    // Formatea el contenido de los elementos con la clase 'intcomma' para que
    // tengan un aspecto numérico por división de miles.
    var intcomma_elements = document.querySelectorAll(".intcomma");
    intcomma_elements.forEach(function(element) {
        element.innerText = intcomma(element.innerText);
    });

    // Ajusta el tamaño del elemento 'main' para que su contenido se muestre completo.
    var main = document.getElementById("main");
    var body = document.querySelector("body");
    main.style.height = body.offsetHeight - 150 + "px";

</script>
</html>

base/templates/base/confirm_delete.html
{% extends 'base/base.html' %}
{% load i18n %}


{% block content %}
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger shadow-sm">
            <h1>{% svg 'trash' fill="var(--danger)" %} {% trans 'Confirmar la eliminación de ' %}{{ object }}</h1>
            <hr>
            <p>{% trans '¿Realmente desea eliminar este registro?' %}</p>
            <input class="btn btn-danger" type="submit" value="{% trans 'Eliminar' %}" />
            <a class="btn btn-secondary" href="{{ object.get_absolute_url }}">{% trans 'Cancelar' %}</a>
        </div>
    </form>
</div>
{% endblock content %}

base/templates/base/detail.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load base %}


{% block actions %}
    {% list_action_links_for_object request object defaults="create list update delete" %}
{% endblock %}


{% block content %}
<div class="container">
    <div class="row bg-white border shadow-sm p-2">
        <div class="col col-0 {% if object.get_img %}col-sm-3{% endif %} p-3">
            {% block detail_img %}
                <img src="{{ object.get_img }}" alt="" class="w-100 h-auto p-2 img-thumbnail bg-light">
            {% endblock detail_img %}
        </div>
        <div class="detail col col-12 {% if object.get_img %}col-sm-9 col-md-8{% endif %}">
            {% block is_not_active %}
                {% if object.is_active == False %}
                    <div class="alert alert-warning">
                        {% svg 'exclamation-triangle' %}
                        {% trans 'Este registro está inactivo.' %}
                    </div>
                {% endif %}
            {% endblock %}
            {% block detail %}
                {% for dic in object.get_object_detail %}
                    <div class="row">
                        <div class="col col-12">
                            {% detail_field request=request name=dic.field.verbose_name.title value=dic.display url=dic.value.get_absolute_url %}
                        </div>
                    </div>
                {% endfor %}
            {% endblock detail %}
        </div>
        <div class="p-2 mt-2 bg-light">
            {% block detail_footer %}
                {% block detail_history %}
                    <div class="row">
                        <div class="col col-12 col-sm-6 col-md-4 col-lg-3">
                            {% if object.has_history %}
                            <button type="button" class="btn btn-outline-secondary w-100 h-100" data-bs-toggle="modal" data-bs-target="#history-modal">
                                {% svg 'clock' %}
                                {% trans 'Historial de cambios' %}
                            </button>
                            {% endif %}
                        </div>
                        {% with object.get_create_history as create_history %}
                            {% if create_history %}
                            <div class="col col-12 col-sm-6 col-md-4 col-lg-3">
                                <div class="text-muted">{% trans 'Creación' %}</div>
                                <div class="fw-bold">{% svg 'person-fill' %} {{ create_history.history_user }}</div>
                                <div class="fw-bold">{% svg 'calendar' %} {{ create_history.history_date }}</div>
                            </div>
                            {% endif %}
                        {% endwith %}
                        {% with object.get_last_update_history as last_update_history %}
                            {% if last_update_history %}
                            <div class="col col-12 col-sm-6 col-md-4 col-lg-3">
                                <div class="text-muted">{% trans 'Última modificación' %}</div>
                                <div class="fw-bold">{% svg 'person-fill' %} {{ last_update_history.history_user }}</div>
                                <div class="fw-bold">{% svg 'calendar' %} {{ last_update_history.history_date }}</div>
                            </div>
                            {% endif %}
                        {% endwith %}
                    </div>
                {% endblock %}
            {% endblock %}
        </div>
    </div>
</div>



<!-- history-modal -->
<div class="modal" tabindex="-1" id="history-modal">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title"></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            {% history object %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans 'Cerrar' %}</button>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

base/templates/base/form.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load bootstrap5 %}


{% block actions %}
    {% list_action_links_for_object request object defaults="create list detail delete" %}
{% endblock %}


{% block content %}
<div class="container-fluid detail">
    {% block form %}
        <form action="" method="POST">
            {% csrf_token %}
            {% block fields %}
                {% bootstrap_form form %}
            {% endblock fields %}
            {{ form.media }}

            {% block buttons %}
            <div class="row">
                <div class="col col-12 col-sm-6">
                    {% block buttons_left %}
                    <input type="submit" class="btn btn-success" value="{% trans 'Guardar' %}">
                    {% endblock %}
                </div>
                <div class="col col-12 col-sm-6 text-end">
                    {% block buttons_right %}
                    {% endblock %}
                </div>
            </div>
            {% endblock buttons %}
        </form>
    {% endblock form %}
</div>
{% endblock content %}

base/templates/base/index.html
{% extends 'base/base.html' %}
{% load i18n %}

{% comment %}
Esta es la plantilla principal para cada site, de modo que en esta enumeramos
las ditintas empresas que pertenecen al site actual.
{% endcomment %}

{% block navbar %}{% endblock %}

{% block frame %}
<main class="container" style="height: 700px;">
    <h1 class="display-3 text-center mb-2">{{ request.site.name }}</h1>

    <div class="row">
        {% for obj in user.get_companies %}
            {% if obj.is_active %}
            <div class="col col-12 col-sm-6 col-md-4 col-lg-3 card text-center shadow-sm" style="width: 18rem;">
                {% if obj.logo %}<img src="{{ obj.logo.url }}" class="card-img-top" alt="{{ obj }}">{% else %}<div class="h2 text-center font-weight-bold p-2 py-4 bg-primary text-light">{{ obj }}</div>{% endif %}
                <div class="card-body">
                <h5 class="card-title">{{ obj }}</h5>
                <p class="card-text">{{ obj.description }}</p>
                <a href="{{ obj.get_absolute_url }}" class="btn btn-primary">{% trans 'Ir a la empresa' %}</a>
                </div>
            </div>
            {% endif %}
        {% endfor %}
        {% for obj in user.company_set.all %}
            {% if obj.is_active %}
            <div class="col col-12 col-sm-6 col-md-4 col-lg-3 card text-center shadow-sm" style="width: 18rem;">
                {% if obj.logo %}<img src="{{ obj.logo.url }}" class="card-img-top" alt="{{ obj }}">{% else %}<div class="h2 text-center font-weight-bold p-2 py-4 bg-dark text-light">{{ obj }}</div>{% endif %}
                <div class="card-body">
                <h5 class="card-title">{{ obj }}</h5>
                <p class="card-text">{{ obj.description }}</p>
                <a href="{{ obj.get_absolute_url }}" class="btn btn-dark">{% trans 'Ir a la empresa' %}</a>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</main>
{% endblock frame %}